FROM jenkins/jenkins:lts

MAINTAINER anup.salokhe@devoteam.com

# Usage: EXPOSE [port]
# EXPOSE 8080
# EXPOSE 50000

# if we want to install via apt
USER root

RUN apt-get update  \
&& curl -sL https://deb.nodesource.com/setup_11.x | bash  \
&& apt-get -y install nodejs \
&& node -v && npm -v \
&& npm install -g newman \
&& newman --version \
&& apt-get install maven -y \
&& mvn --version 

##to give access to jenkins user
##RUN chown -R jenkins:jenkins /var/jenkins_home
##COPY --chown=jenkins:jenkins ./soapui/ /opt/soapui/ (Try this)

# drop back to the regular jenkins user - good practice
#USER jenkins